"""Scheme change due to SCM support moving to a plugin

Revision ID: 47ebe0522809
Revises: 
Create Date: 2016-06-08 11:29:16.460075

"""

# revision identifiers, used by Alembic.
revision = '47ebe0522809'
down_revision = None
branch_labels = None
depends_on = None

import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('distgit_dir', sa.String()))
    commits = table('commits',
                    column('id', sa.Integer),
                    column('repo_dir', sa.String),
                    column('distgit_dir', sa.String))
    op.execute(commits.update()\
               .where(commits.c.id==commits.c.id)\
               .values(distgit_dir = (commits.c.repo_dir + "_distro")))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'distgit_dir')
    ### end Alembic commands ###
