#!/bin/bash -xe

# Function to run at the end of each rpm build (success and failure)
# Files produced on the volume need to have their ownership changed from root.
function finalize(){
    rm -rf ${TOP_DIR}
}
