#!/bin/bash
# This script redirects to dlrn. It's a shell script to avoid python2/3
# conflicts.

executable="dlrn"
msg="Using the command 'delorean' has been deprecated. Redirecting to '$executable $@'.\n"\

echo -e $msg >&2
exec $executable "$@"
