#!/usr/bin/env python
# Maps repository names to rdoinfo package names
# package names are all either exact matches or prefixed with either
# "python-" or "openstack-", so we just check that the ends match

import sys

from rdopkg.actionmods import rdoinfo

if len(sys.argv) == 3:
    rdoinfo_url = sys.argv[2]
else:
    rdoinfo_url = "https://github.com/redhat-openstack/rdoinfo.git"

inforepo = rdoinfo.RdoinfoRepo(".", rdoinfo_url)
inforepo.init()

for package in inforepo.get_info()["packages"]:
    if (package["name"].endswith(sys.argv[1]) or
        "project" in package and package["project"].endswith(sys.argv[1])):
        print package["name"]
        exit(0)
exit(1)
