#!/bin/env python
# Maps repository names to rdoinfo package names
# package names are all either exact matches or prefixed with either
# "python-" or "openstack-", so we just check that the ends match

import sys

from rdopkg.actionmods import rdoinfo

inforepo = rdoinfo.RdoinfoRepo(".", "https://github.com/redhat-openstack/rdoinfo.git")
inforepo.init()

for package in inforepo.get_info()["packages"]:
    if package["name"].endswith(sys.argv[1]):
        print package["name"]
        exit(0)
exit(1)
