---
- hosts: all
  tasks:
    - name: "Run sphinx-build"
      command: sphinx-build -W -b html -d build/doctrees docs/ {{ ansible_user_dir }}/zuul-output/logs/docs-html/
      args:
        chdir: "{{ zuul.project.src_dir }}"
