---
- hosts: all
  tasks:
    - name: Install test-requirements for building Spinx doc
      pip:
        requirements: "{{ zuul.project.src_dir }}/test-requirements.txt"

    - name: "Run sphinx-build"
      command: sphinx-build -W -b html -d build/doctrees doc/source {{ ansible_user_dir }}/zuul-output/logs/docs-html/
      args:
        chdir: "{{ zuul.project.src_dir }}"
