---
- hosts: all
  vars:
    working_dir: '/workspace/{{ zuul.project.src_dir }}'
  tasks:
    - name: Install test-requirements for building Spinx doc
      pip:
        requirements: "{{ working_dir }}/doc/requirements.txt"

    - name: "Run sphinx-build"
      command:
        "sphinx-build -W -b html -d build/doctrees doc/source {{ ansible_user_dir }}/zuul-output/logs/docs-html/"
      args:
        chdir: "{{ working_dir }}"
