---
- hosts: upstream-centos-8-stream
  tasks:
    - name: Install krb5-devel
      package:
        name:
          - krb5-devel
        state: present
      become: true

    - name: Install krb5-workstation
      package:
        name:
          - krb5-workstation
        state: present
      become: true