---
- hosts: test-node
  tasks:
    - name: Create directory for tripleo data
      file:
        path: '{{ ansible_user_dir }}/tripleo'
        state: directory

    - name: Copy contents of DLRN to tripleo data directory
      shell:
        cmd: |
          mkdir {{ ansible_user_dir }}/tripleo/delorean
          cp -pr src/{{ zuul.project.canonical_hostname }}/* {{ ansible_user_dir }}/tripleo/delorean

    - name: Clone tripleo-ci repository
      git:
        repo: 'https://github.com/openstack-infra/tripleo-ci'
        dest: '{{ ansible_user_dir }}/tripleo'

    - name: Ensure log directory is created
      file:
        path: '{{ ansible_user_dir }}/tripleo/delorean/logs'
        state: directory

    - name: Execute tripleo.sh
      shell:
        cmd: |
          scripts/tripleo.sh --delorean-setup
          scripts/tripleo.sh --delorean-build openstack/tripleo-heat-templates
        chdir: "{{ ansible_user_dir }}/"

    - name: List RPM files, fail if there is an error
      shell:
        cmd: |
            ls "{{ ansible_user_dir }}/tripleo/delorean/data/repos/current/*.rpm | grep -v src.rpm"

    - name: Move artifacts to the log directory
      synchronize:
        src: '{{ ansible_user_dir }}/tripleo/delorean/data/repos'
        dest: '{{ ansible_user_dir }}/tripleo/delorean/logs'
